version: "1"
services:
    webserver:
        build: ./docker/php/
        ports:
            - "0.0.0.0:${APP_PORT}:80"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        command: sh -c "composer install && apachectl -D FOREGROUND"
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "0.0.0.0:10500:${DB_PORT}"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ./mysql/lib:/var/lib/mysql
